### ISSUE TITLE
Can you tell me how can I get Calculation data?

### ISSUE THREAD

**Issue by JJ306** [huaxiao87/Perception_Neuron_Data_Sender#1]
I am looking for how can I use ShowBvhCalcInfo(...) function? This function is used to get calculation data. 

Thank you

**Comment by solenebreton20** [comment]
I would like to know if you have succeeded to code and use the function ShowBvhCalcInfo ?
Thank you

**Comment by solenebreton20** [comment]
> I am looking for how can I use ShowBvhCalcInfo(...) function? This function is used to get calculation data.
> 
> Thank you

I would like to know if you have succeeded to code and use the function ShowBvhCalcInfo ?
Thank you
